name: Percy visual tests

# Trigger on pull requests (and optionally pushes to main if you like)
on:
  pull_request:
    branches: [ main ]

jobs:
  visual_tests:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install deps
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build your app
      - name: Build
        run: npm run build

      # 5️⃣ Serve the build in the background on port 3001
      - name: Serve production build
        run: npx serve -s build -l 3001 &

      # 6️⃣ Wait for the server to be ready
      - name: Wait for server
        run: npx wait-on http://localhost:3001

      # 7️⃣ Run Percy snapshot
      - name: Percy snapshot
        uses: percy/exec-action@v0.3.1
        with:
          command: npx percy snapshot snapshots.yml
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}